### ISSUE TITLE
Issue with Influenza characterization on BQ

### ISSUE THREAD

**Issue by jdposada** [edward-burn/OHDSI-COVID19-HopitalisationsCharacterisation#1]
Attached the error message

<img width="1403" alt="Screen Shot 2020-03-28 at 5 38 41 PM" src="https://user-images.githubusercontent.com/11167042/77837208-69b8dd00-711b-11ea-94fd-519ccd410e5c.png">

**Comment by jdposada** [comment]
Now I am getting a different one. The one above was related with the default runAsBatch=FALSE in the executeSQL function

<img width="1409" alt="Screen Shot 2020-03-28 at 6 47 13 PM" src="https://user-images.githubusercontent.com/11167042/77838028-b8b74000-7124-11ea-87ef-211c8f4acd8d.png">

**Comment by edward-burn** [comment]
Thanks @anthonysena, this should hopefully now be fixed
