### ISSUE TITLE
Issue running the infuenza package

### ISSUE THREAD

**Issue by PRijnbeek** [edward-burn/OHDSI-COVID19-HopitalisationsCharacterisation#5]
All running well, but i get the message below. It seems it still has covid-19 concept sets? a bit strange.

I can skip the orphan part if needed cohorts were created fine.

Creating concept counts table
  |==============================================================================================================================================| 100%
Executing SQL took 8.14 mins
- Finding orphan concepts for concept set COVID-19 (including asymptomatic)
Error in if (item$isExcluded) { : argument is of length zero

**Comment by gaowx3** [comment]
Hi Influenze package users,

I ran the "InfluenzaHospCohortDiag" package and got some errors. The issues seemed  to relate to sql queries. Here is error log. May you help me for this issue? 

Thanks,
Weihua
*******************************************************************************    
DBMS:
impala


Error:
java.sql.SQLException: [Cloudera][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Possible loss of precision for target table 'rwd_p_omop_truven_medicaid_results2.p1vw8d9jcov_ref'.
Expression 'CAST('time (days) between cohort start and end' AS STRING)' (type: STRING) would need to be cast to VARCHAR(512) for column 'covariate_name'
), Query: INSERT INTO `rwd_p_omop_truven_medicaid_results2`.`p1vw8d9jcov_ref` (`covariate_id`,`covariate_name`,`analysis_id`,`concept_id`) SELECT `t1`.`covariate_id`, CAST( 'time (days) between cohort start and end' AS string ) as `covariate_name`, 10 as `analysis_id`, 0 as `concept_id` FROM (SELECT DISTINCT `p1vw8d9jcov_1`.`covariate_id` FROM `rwd_p_omop_truven_medicaid_results2`.`p1vw8d9jcov_1`) AS t1.


SQL:
INSERT INTO rwd_p_omop_truven_medicaid_results2.p1vw8d9jcov_ref (
    covariate_id,
    covariate_name,
    analysis_id,
    concept_id
    )
SELECT covariate_id,
 
 


    CAST('time (days) between cohort start and end' AS VARCHAR(512)) AS covariate_name,


    10 AS analysis_id,
    0 AS concept_id
FROM (
    SELECT DISTINCT covariate_id
    FROM rwd_p_omop_truven_medicaid_results2.p1vw8d9jcov_1
    ) t1


R version:
R version 3.6.0 (2019-04-26)


Platform:
x86_64-redhat-linux-gnu


Attached base packages:
- stats
- graphics
- grDevices
- utils
- datasets
- methods
- base


Other attached packages:
- InfluenzaHospCohortDiag (0.0.1)
- DatabaseConnector (2.4.2)

**Comment by edward-burn** [comment]
Issue with orphan concepts should now be fixed (was due to redundant, COVID-19, concept sets that have now been removed). @gaowx3 I have made yours a separate issue #9

**Comment by gaowx3** [comment]
Thank you, Ed for the updates. I will rerun the package and keep you posted if there is any issues.
